%% CT Concentration Analysis and Transport Metrics Extraction
%
% This script extracts quantitative transport information from processed
% concentration images generated from CT experiments.
%
% Concentration images previously stored in HDF5 format are analyzed to
% compute spatial concentration profiles, breakthrough curves, mixing-zone
% characteristics, and concentration-front velocities.
%
% The resulting variables are consolidated into a structured MATLAB object
% and saved for downstream visualization and comparative analysis.
%
% Workflow
% --------
% 1. Import experiment metadata and configuration.
% 2. Load scanner metadata (.pca, .pcj, .pcp).
% 3. Read concentration images from HDF5 storage.
% 4. Compute concentration statistics for each image:
%       - Axial concentration profile
%       - Vertical concentration profile
%       - Concentration histogram
%       - Injected pore volumes
%       - Dimensionless time
% 5. Determine concentration-front locations:
%       - C = 0.1 front
%       - C = 0.9 front
%       - Front width
% 6. Construct breakthrough curves.
% 7. Estimate front propagation velocity.
% 8. Generate contour-based front maps.
% 9. Compute apparent velocity fields from contour displacement.
% 10. Save all processed variables into a MATLAB structure.
%
% Inputs
% ------
% inputCTExpConfig.xlsx
%     Repository configuration file.
%
% Processed HDF5 files
%     Generated by the image processing workflow and containing:
%
%         /exp/run_xx/conc
%
%     where each dataset is a stack of concentration images.
%
% Scanner Metadata
% ----------------
% .pca
%     Scanner and reconstruction parameters.
%
% .pcp
%     Acquisition timestamps and scan information.
%
% .pcj
%     Reconstruction metadata.
%
% Outputs
% -------
% One MAT file per experiment:
%
%     <ExperimentKey>.mat
%
% containing:
%
%     CFparams
%     BTlinesBefore
%     BTcore
%     concVarsAll
%     refInit
%     refFinal
%     exp
%
% Key Quantities Calculated
% -------------------------
%
% C1Profile
%     Cross-sectionally averaged concentration as a function of core
%     length:
%
%         C1(z)
%
% C1Axial
%     Laterally averaged concentration as a function of horizontal
%     position:
%
%         C1(x)
%
% BTcore
%     Breakthrough curve based on outlet concentration.
%
% BTlinesBefore
%     Breakthrough curve based on inlet concentration.
%
% zFront10
%     Mean position of the C = 0.1 concentration contour.
%
% zFront90
%     Mean position of the C = 0.9 concentration contour.
%
% zWidth
%     Mixing-zone width:
%
%         zWidth = zFront10 - zFront90
%
% tDcorr
%     Corrected dimensionless time based on measured front velocity.
%
% Velocity Field Analysis
% -----------------------
%
% Concentration contours from:
%
%     C = 0.1, 0.2, ..., 0.9
%
% are tracked between consecutive images.
%
% Displacements are converted into:
%
%     uz_field   Vertical front velocity [cm/s]
%
% providing a simple estimate of concentration-front motion throughout
% the experiment.
%
% Dependencies
% ------------
%
%     import_inputCTExp
%     importPCA
%     importPCP
%     importPCJ
%
% MATLAB Functions
% ----------------
%
%     h5read
%     h5info
%     histcounts
%     gradient
%
% Notes
% -----
%
% Front positions are estimated using concentration bands:
%
%     0.05 ≤ C ≤ 0.15   -> C = 0.1 front
%     0.85 ≤ C ≤ 0.95   -> C = 0.9 front
%
% Concentration contour maps are generated using concentration intervals:
%
%     C = 0.1 : 0.1 : 0.9
%
% These contour maps are used solely for front tracking and velocity-field
% estimation.

%% IMPORT input

Root = CT_setupPaths;

% Introduce name of input and desired output folder name

inputFileConfigName = 'inputCTExpConfig.xlsx';
inputFileConfig = readtable(inputFileConfigName);


%% Extract data from images

for i = 1:height(inputFileConfig)

    filenameExp = inputFileConfig.inputFileName{i};

    pathImportAll = inputFileConfig.importPath{i}; % Path for OUTPUT
    pathExportAll = inputFileConfig.exportPath{i}; % Path for OUTPUT
    mkdir(pathExportAll); % Create directory for output

    filedataExp = import_inputCTExp(filenameExp); % import input to a local variable

    % MFM analog (CT) data for this experiment — source of D
    pathImport_MFM_CT = regexprep(inputFileConfig.MFM_BTC_CT_Path{i}, '^(\.\./)+', '');
    MFM_CT_name = inputFileConfig.MFM_BTC_CT_Key{i};
    MFM_CT_file = fullfile(Root, pathImport_MFM_CT, 'expProcFullData.mat');

    if ~isfile(MFM_CT_file)
        error('MFM results file not found: %s', MFM_CT_file);
    end
    MFM_CT_Data = load(MFM_CT_file);
    expProcFullData_MFM_CT = MFM_CT_Data.expProcFullData.(MFM_CT_name);

    % experiment data all in cm (not m) and min (not seconds)
    Ci = filedataExp.C1init/100;
    Cj = filedataExp.C1j/100;
    uint_cm2min = filedataExp.Q/(filedataExp.phi*pi*((filedataExp.D*2.54/2)^2));     % u interstitial theoretical
    L_cm = filedataExp.L*2.54; 
    D = expProcFullData_MFM_CT.exp_params.D12_cm2min;

    % Capture init ref data folder
    refInitFolderContent = dir(filedataExp.path+filedataExp.CT_data_ref_init); % Xe
    refInitFolderContent = refInitFolderContent([refInitFolderContent.isdir] & ~startsWith({refInitFolderContent.name},'.'));
    refInitFolderName = refInitFolderContent.name;
    
    % Capture final ref data folder
    refFinalFolderContent = dir(filedataExp.path+filedataExp.CT_data_ref_final); % He
    refFinalFolderContent = refFinalFolderContent([refFinalFolderContent.isdir] & ~startsWith({refFinalFolderContent.name},'.'));
    refFinalFolderName = refFinalFolderContent.name;
    
    % Capture exp data folder
    expFolderContent = dir(filedataExp.path+filedataExp.CT_data_exp); % exp
    expFolderContent = expFolderContent([expFolderContent.isdir] & ~startsWith({expFolderContent.name},'.'));
    expFolderName = {expFolderContent.name}';
    expFolderPath = {expFolderContent.folder};
    
    % BT extract
    expCTData = struct();

    % Image
    HDF5filename = fullfile(pathExportAll, filedataExp.Key + ".h5");

    % CF params
    expCTData.(filedataExp.Key).CFparams = filedataExp;

    % CT init ref
    refInitFolderPathCT = fullfile(refInitFolderContent.folder, refInitFolderName);
        % pca
        refInitpcaFiles = dir(fullfile(refInitFolderPathCT, '*.pca'));
        expCTData.(filedataExp.Key).refInit.pca = importPCA(refInitpcaFiles);
        % pcj 
        refInitpcjFiles = dir(fullfile(refInitFolderPathCT, '*.pcj'));
        expCTData.(filedataExp.Key).refInit.pcj = importPCJ(refInitpcjFiles);
        % pcp
        refInitpcpFiles = dir(fullfile(refInitFolderPathCT, '*.pcp'));
        expCTData.(filedataExp.Key).refInit.pcp = importPCP(refInitpcpFiles);
        % CTimages folder 
        
    nn_refInit = height(expCTData.(filedataExp.Key).refInit.pcp);

    % CT final ref
    refFinalFolderPathCT = fullfile(refFinalFolderContent.folder, refFinalFolderName);
        % pca
        refFinalpcaFiles = dir(fullfile(refFinalFolderPathCT, '*.pca'));
        expCTData.(filedataExp.Key).refFinal.pca = importPCA(refFinalpcaFiles);
        % pcj 
        refFinalpcjFiles = dir(fullfile(refFinalFolderPathCT, '*.pcj'));
        expCTData.(filedataExp.Key).refFinal.pcj = importPCJ(refFinalpcjFiles);
        % pcp
        refFinalpcpFiles = dir(fullfile(refFinalFolderPathCT, '*.pcp'));
        expCTData.(filedataExp.Key).refFinal.pcp = importPCP(refFinalpcpFiles);

    % BT varsAll
    rhoNormVarsAll = table();
    concVarsAll = table();

    % interpolant for composition form array 0 to 1 (binary mixture)
    interpFcn = buildInterpolant(filedataExp.Fluid1, ...
        filedataExp.Fluid2, filedataExp.T, filedataExp.P);
    
    % zD levels for spatially-resolved BTC extraction (zD=0 is BTlinesBefore; zD=1 is outlet BTcore)
    zDlevels = 0:0.1:1.0;
    zDBTC_rhoNorm = cell(length(zDlevels),1);
    zDBTC_conc    = cell(length(zDlevels),1);
    for m = 1:length(zDlevels)
        zDBTC_rhoNorm{m} = table();
        zDBTC_conc{m} = table();
    end

    for j = 1:length(expFolderName)
        expFolderPathCT = fullfile(expFolderPath{j}, expFolderName{j});
        run_name = "run_" + sprintf('%02d', j);
            % pca
            exppcaFiles = dir(fullfile(expFolderPathCT, '*.pca'));
            expCTData.(filedataExp.Key).exp.(run_name).pca = importPCA(exppcaFiles);
            % pcj 
            exppcjFiles = dir(fullfile(expFolderPathCT, '*.pcj'));
            expCTData.(filedataExp.Key).exp.(run_name).pcj = importPCJ(exppcjFiles);
            % pcp
            exppcpFiles = dir(fullfile(expFolderPathCT, '*.pcp'));
            expCTData.(filedataExp.Key).exp.(run_name).pcp = importPCP(exppcpFiles);

        nn_exp = height(expCTData.(filedataExp.Key).exp.(run_name).pcp); % per run

        HDF5dataPath = ['/exp/' char(run_name) '/conc'];  % structured path
        info = h5info(HDF5filename, HDF5dataPath);
        dims = info.Dataspace.Size;
        nx = dims(1);
        ny = dims(2);
        nz = dims(3);
        
        for k = 1:nn_exp
            % Concentration profiles and histograms of normalized images
            imgNr = expCTData.(filedataExp.Key).exp.(run_name).pcp.ImgNr(k);
            rotPos = expCTData.(filedataExp.Key).exp.(run_name).pcp.RotPos(k);
            timeStamp = expCTData.(filedataExp.Key).exp.(run_name).pcp.Time(k);
            timeStart = filedataExp.st;
            timeElapsed = timeStamp - timeStart;
            secondsElapsed = seconds(timeElapsed);
            volInjected = secondsElapsed*filedataExp.Q/60;
            tDtotal = volInjected/filedataExp.Vtotal;

            rhoNormImage = h5read(HDF5filename, HDF5dataPath, [1 1 k], [nx ny 1]);
            concImage = interpFcn(rhoNormImage);

            resXmm = expCTData.(filedataExp.Key).exp.(run_name).pca.Geometry.VoxelSizeX;
            resYmm = expCTData.(filedataExp.Key).exp.(run_name).pca.Geometry.VoxelSizeY;

            rhoNormVars_k = populate_CTframeVars(rhoNormImage, resXmm, resYmm, ...
                imgNr, rotPos, timeStamp, timeElapsed, secondsElapsed, volInjected, tDtotal,D,uint_cm2min);
            expCTData.(filedataExp.Key).exp.(run_name).vars.rhoNorm(k) = rhoNormVars_k;
            
            concVars_k = populate_CTframeVars(concImage, resXmm, resYmm, ...
                imgNr, rotPos, timeStamp, timeElapsed, secondsElapsed, volInjected, tDtotal,D,uint_cm2min);
            expCTData.(filedataExp.Key).exp.(run_name).vars.conc(k) = concVars_k;
            
        end

        rhoNormVars_temp = expCTData.(filedataExp.Key).exp.(run_name).vars.rhoNorm;
        rhoNormVars_tempTable = struct2table(rhoNormVars_temp,'AsArray',true);
        rhoNormVarsAll = [rhoNormVarsAll;rhoNormVars_tempTable];

        concVars_temp = expCTData.(filedataExp.Key).exp.(run_name).vars.conc;
        concVars_tempTable = struct2table(concVars_temp,'AsArray',true);
        concVarsAll = [concVarsAll;concVars_tempTable];

    end
    
    u_SI = uint_cm2min/(60*10000);
    L_SI = L_cm/100;
    dt_guess = 0;
    Cmin = 0.16; Cmax = 0.84;

    zDlevels_KLfit = 0.1:0.1:1.0;
    
    % rho norm
    varsAll_rn = rhoNormVarsAll;
    KL_fit_byZD_rn = struct();
    BTCMetrics_byZD_rn = struct();
    for m = 1:length(zDlevels_KLfit)
        zD = zDlevels_KLfit(m);
        fieldName = strrep(sprintf('zD%.1f', zD), '.', 'p');   % zD0p1 ... zD1p0
        CfieldName = strrep(sprintf('CD1_zD%.1f', zD), '.', 'p');
        
        C_at_zD = varsAll_rn.(CfieldName);
        t_vals  = varsAll_rn.secondsElapsed;
        tD_vals = varsAll_rn.tDtotal;
        L_eff   = zD * L_SI;

        % KL fit from BTC_CT
        [methods_m, bestMethod_m, best_m] = fitBTC_KL_allMethods( ...
            t_vals, C_at_zD, ones(height(varsAll_rn),1), ...
            u_SI, Cj, Ci, L_eff, dt_guess, Cmin, Cmax);

        KL_fit_byZD_rn.(fieldName) = struct('zD',zD,'L_eff',L_eff, ...
            'allMethods',methods_m,'bestMethod',bestMethod_m,'best',best_m);

        % BTC metrics at this zD
        [C_unique, idx] = unique(C_at_zD,'stable');
        t_unique  = t_vals(idx);
        tD_unique = tD_vals(idx);
        BTCMetrics_byZD_rn.(fieldName) = getBTCMetrics(t_unique, tD_unique, C_unique);
    end
    
    expCTData.(filedataExp.Key).varsAll.rhoNorm = rhoNormVarsAll;
    expCTData.(filedataExp.Key).resultsAll.rhoNorm.KL_BTC_CT_byZD = KL_fit_byZD_rn;
    expCTData.(filedataExp.Key).resultsAll.rhoNorm.BTCMetrics_byZD = BTCMetrics_byZD_rn;
    % at zd = 1.0 (outlet of the core)
    expCTData.(filedataExp.Key).resultsAll.rhoNorm.KL_BTC_CT = KL_fit_byZD_rn.zD1p0;
    expCTData.(filedataExp.Key).resultsAll.rhoNorm.BTCMetrics = BTCMetrics_byZD_rn.zD1p0;
    % KL from average fronts
    validKL = ~isnan(rhoNormVarsAll.KL_CT);
    expCTData.(filedataExp.Key).resultsAll.rhoNorm.KL_front_CT.KL_cm2min_mean = ...
        mean(expCTData.(filedataExp.Key).varsAll.rhoNorm.KL_CT(validKL));
    expCTData.(filedataExp.Key).resultsAll.rhoNorm.KL_front_CT.KL_cm2min_std = ...
        std(expCTData.(filedataExp.Key).varsAll.rhoNorm.KL_CT(validKL));
    expCTData.(filedataExp.Key).resultsAll.rhoNorm.KL_front_CT.nValidFrames = sum(validKL);

    % conc
    varsAll_c = concVarsAll;
    KL_fit_byZD_c = struct();
    BTCMetrics_byZD_c = struct();
    for m = 1:length(zDlevels_KLfit)
        zD = zDlevels_KLfit(m);
        fieldName = strrep(sprintf('zD%.1f', zD), '.', 'p');   % zD0p1 ... zD1p0
        CfieldName = strrep(sprintf('CD1_zD%.1f', zD), '.', 'p');
        
        C_at_zD = varsAll_c.(CfieldName);
        t_vals  = varsAll_c.secondsElapsed;
        tD_vals = varsAll_c.tDtotal;
        L_eff   = zD * L_SI;

        % KL fit from BTC_CT
        [methods_m, bestMethod_m, best_m] = fitBTC_KL_allMethods( ...
            t_vals, C_at_zD, ones(height(varsAll_c),1), ...
            u_SI, Cj, Ci, L_eff, dt_guess, Cmin, Cmax);

        KL_fit_byZD_c.(fieldName) = struct('zD',zD,'L_eff',L_eff, ...
            'allMethods',methods_m,'bestMethod',bestMethod_m,'best',best_m);

        % BTC metrics at this zD
        [C_unique, idx] = unique(C_at_zD,'stable');
        t_unique  = t_vals(idx);
        tD_unique = tD_vals(idx);
        BTCMetrics_byZD_c.(fieldName) = getBTCMetrics(t_unique, tD_unique, C_unique);
    end
    
    expCTData.(filedataExp.Key).varsAll.conc = concVarsAll;
    expCTData.(filedataExp.Key).resultsAll.conc.KL_BTC_CT_byZD = KL_fit_byZD_c;
    expCTData.(filedataExp.Key).resultsAll.conc.BTCMetrics_byZD = BTCMetrics_byZD_c;
    % at zd = 1.0 (outlet of the core)
    expCTData.(filedataExp.Key).resultsAll.conc.KL_BTC_CT = KL_fit_byZD_c.zD1p0;
    expCTData.(filedataExp.Key).resultsAll.conc.BTCMetrics = BTCMetrics_byZD_c.zD1p0;
    % KL from average fronts
    validKL = ~isnan(concVarsAll.KL_CT);
    expCTData.(filedataExp.Key).resultsAll.conc.KL_front_CT.KL_cm2min_mean = ...
        mean(expCTData.(filedataExp.Key).varsAll.conc.KL_CT(validKL));
    expCTData.(filedataExp.Key).resultsAll.rhoNorm.KL_front_CT.KL_cm2min_std = ...
        std(expCTData.(filedataExp.Key).varsAll.conc.KL_CT(validKL));
    expCTData.(filedataExp.Key).resultsAll.conc.KL_front_CT.nValidFrames = sum(validKL);

    % save expCTData
    expCT_name = pathExportAll + filedataExp.Key;
    expCTDataSave = expCTData.(filedataExp.Key);
    save(expCT_name + '.mat','expCTDataSave','-v7.3')
end


%% 
% width from this algorith not likely ame width from contours algorithm
% add KL from width, how it changes with time, 
% then add average ok that KL and std, 
% then solve KL from BTC CT at zD = 1, zd = 0.8, zd = 0.6, zd = 0.4, zd = 0.2, zd = 0 (lines)
% add to data CT saved