
%% Comparative Analysis of CT-Derived Concentration Profiles
%
% This script compares concentration distributions and breakthrough curves
% from multiple CT experiments. Experimental results are loaded from
% previously processed MATLAB datasets and plotted together to facilitate
% comparison between experimental conditions.
%
% Workflow
% --------
% 1. Load experiment configurations from a master spreadsheet.
% 2. Import processed concentration data for each experiment.
% 3. Search for the concentration profile closest to a user-defined
%    concentration-location target.
% 4. Extract the selected concentration profile.
% 5. Plot concentration profiles from all experiments.
% 6. Plot corresponding breakthrough curves for comparison.
%
% Analysis Performed
% ------------------
%
% Profile Selection:
%   For each experiment, the script searches all available concentration
%   profiles and identifies the profile whose concentration distribution
%   passes closest to a specified target coordinate:
%
%       (Z_target, C_target)
%
%   This allows profiles from different experiments to be compared at
%   approximately equivalent displacement states.
%
% Concentration Profile Comparison:
%   Displays averaged concentration profiles along the core length:
%
%       C1(Z)
%
%   for the selected experimental state.
%
% Breakthrough Curve Comparison:
%   Displays outlet concentration as a function of time:
%
%       C1(t)
%
%   allowing comparison of displacement dynamics between experiments.
%
% Inputs
% ------
% inputCTExpConfig.xlsx
%     Configuration file containing paths to processed experimental data.
%
% Experiment MAT Files
%     Generated by the CT processing workflow and containing:
%
%         VarsAll
%         CFparams
%
% User Parameters
% ---------------
% Z_target
%     Target axial position [cm].
%
% C_target
%     Target concentration [-].
%
% Outputs
% -------
% Figure 1:
%     Comparison of selected axial concentration profiles.
%
% Figure 2:
%     Comparison of breakthrough curves.
%
% Dependencies
% ------------
%     import_inputCTExp
%
% Notes
% -----
% The profile selected for each experiment corresponds to the minimum
% Euclidean distance:
%
%     d² = (Z - Z_target)² + (C - C_target)²
%
% between the profile and the target reference point.


%% IMPORT input

Root = CT_setupPaths;

% Introduce name of input and desired output folder name

inputFileConfigName = 'inputCTExpConfig.xlsx';
inputFileConfig = readtable(inputFileConfigName);
exportPath = 'results/';

dataSource = 'conc';   % 'conc' or 'rhoNorm' — applies to ALL comparisons in this script
if ~ismember(dataSource, {'rhoNorm','conc'})
    error('dataSource must be "rhoNorm" or "conc", got "%s"', dataSource);
end

%% Load data
nExp = height(inputFileConfig);
filedataExpAll = cell(nExp,1);
expCTDataAll   = cell(nExp,1);
MFM_CT_DataAll     = cell(nExp,1);
MFM_UHS_DataAll    = cell(nExp,1);

for i = 1:nExp
    filenameExp   = inputFileConfig.inputFileName{i};
    pathExportAll = inputFileConfig.exportPath{i};

    filedataExpAll{i} = import_inputCTExp(filenameExp);
    
    % CT
    expCTDataname = fullfile(pathExportAll, filedataExpAll{i}.Key + ".mat");
    temp = load(expCTDataname);
    expCTDataAll{i} = temp.expCTDataSave;

    % MFM analog (CT) and MFM UHS data
    pathImport_MFM_CT  = inputFileConfig.MFM_BTC_CT_Path{i};
    pathImport_MFM_UHS = inputFileConfig.MFM_BTC_UHS_Path{i};
    MFM_CT_name  = inputFileConfig.MFM_BTC_CT_Key{i};
    MFM_UHS_name = inputFileConfig.MFM_BTC_UHS_Key{i};

    MFM_CT_file  = fullfile(Root, pathImport_MFM_CT,  'expProcFullData.mat');
    MFM_UHS_file = fullfile(Root, pathImport_MFM_UHS, 'expProcFullData.mat');

    MFM_CT_Data  = load(MFM_CT_file);
    MFM_UHS_Data = load(MFM_UHS_file);

    MFM_CT_DataAll{i}  = MFM_CT_Data.expProcFullData.(MFM_CT_name);
    MFM_UHS_DataAll{i} = MFM_UHS_Data.expProcFullData.(MFM_UHS_name);
end

%% Find where to plot profile
% Plot Z Profile at fixed zD

colours = {[0.318 0.654 0.976],[0.09 0.306 0.525], [0.435 0.753 0.251],[0.059 0.361 0.102] }; %light blue, dark blue, light green, dark green

ZD_target = 0.5;
CD_target = 0.5;

ZD_found = [];
CD_found = [];
idx_found = [];
l_found = [];

figure
legendEntries = cell(1, height(inputFileConfig));

for i = 1:nExp
    filedataExp = filedataExpAll{i};
    vars = expCTDataAll{i}.varsAll.(dataSource);

    best_dist = inf;
    best_ZD = NaN;
    best_CD = NaN;
    best_idx = NaN;
    best_l = NaN;

    for l = 1:height(vars)

        C1Profile = vars.C1Profile{l};

        ZD = C1Profile.zDimLess;
        CD = C1Profile.CVert;

        dist = (ZD - ZD_target).^2 + (CD - CD_target).^2;

        [min_dist, idx] = min(dist);

        if min_dist < best_dist
            best_dist = min_dist;
            best_ZD = ZD(idx);
            best_CD = CD(idx);
            best_idx = idx;
            best_l = l;
        end
    end

    ZD_found(i) = best_ZD;
    CD_found(i) = best_CD;
    idx_found(i) = best_idx;
    l_found(i) = best_l;

    % what profile to plot
    C1Profile_plot = vars.C1Profile{l_found(i)};
    tD = vars.tDtotal(l_found(i));
    legendEntries{i} = filedataExp.Key;

    % plot
    plot(C1Profile_plot.zDimLess, C1Profile_plot.CVert,'LineWidth',3,'Color',colours{:,i})
    xlabel('Z_D [-]','FontSize',14)
    ylabel('C_1 [-]','FontSize',14)
    set(gca, 'FontSize', 14)
    grid on
    hold on

end
legend(legendEntries, 'Interpreter','none','FontSize',9.8)

%% Find where to plot profile
% Plot Z Profile at fixed tD

colours = {[0.318 0.654 0.976],[0.09 0.306 0.525], [0.435 0.753 0.251],[0.059 0.361 0.102] }; %light blue, dark blue, light green, dark green
% tD_target = 0.5;
tD_target = 0.5:0.1:1.2;

for m=1:length(tD_target)
    tD_found = nan(height(inputFileConfig),1);
    l_found  = nan(height(inputFileConfig),1);
    
    fig = figure;
    legendEntries = cell(1, height(inputFileConfig));
    
    for i = 1:height(inputFileConfig)
        filedataExp = filedataExpAll{i};   
        vars = expCTDataAll{i}.varsAll.(dataSource);
    
        % find the scan (row) whose tDtotal is closest to target
        [minDist, l] = min(abs(vars.tDtotal - tD_target(m)));
        if minDist > 0.05   % flag if the nearest available scan is far from target
            warning('%s: nearest scan is tD=%.3f (target %.3f, off by %.3f)', ...
                filedataExp.Key, vars.tDtotal(l), tD_target(m), minDist);
        end
    
        tD_found(i) = vars.tDtotal(l);
        l_found(i)  = l;
    
        % plot that scan's spatial profile
        C1Profile_plot = vars.C1Profile{l};
        legendEntries{i} = char(filedataExp.Key) + sprintf(" (t_D=%.2f)", tD_found(i));
    
        % plot
        plot(C1Profile_plot.zDimLess, C1Profile_plot.CVert,'LineWidth',3,'Color',colours{:,i})
        xlabel('Z_D [-]','FontSize',14)
        ylabel('C_1 [-]','FontSize',14)
        xlim([0,1])
        ylim([0,1])
        set(gca, 'FontSize', 14)
        grid on
        hold on
    
    end
    if tD_target(m) < 0.8
        legend(legendEntries, 'Interpreter','none','FontSize',8,'Location','northeast')
    else
        legend(legendEntries, 'Interpreter','none','FontSize',8,'Location','southwest')
    end
    title(sprintf('Z profiles (%s) @ tD = %.1f', dataSource,tD_target(m)),'Interpreter','none')
    % save the completed figure for this selection
    tDStr = strrep(sprintf('%.1f', tD_target(m)), '.', 'p');  % e.g. 0.50 -> 0p50
    fname = sprintf('Zprofiles_%s_tD%s', dataSource,tDStr);
    saveas(fig, fullfile(exportPath, fname), 'png');
    saveas(fig, fullfile(exportPath, fname), 'fig');
end


%% BTC dimension time
colours = {[0.318 0.654 0.976],[0.09 0.306 0.525], [0.435 0.753 0.251],[0.059 0.361 0.102] }; %light blue, dark blue, light green, dark green

fig = figure;
legendEntries = cell(1, height(inputFileConfig));

for i = 1:height(inputFileConfig)
    filedataExp = filedataExpAll{i}; 
    vars = expCTDataAll{i}.varsAll.(dataSource);
    CfieldOutlet = 'CD1_zD1p0';

    legendEntries{i} = "CT"+filedataExp.Key;

    % plot
    plot(vars.timeElapsed, vars.(CfieldOutlet),'LineWidth',2,'Color',colours{:,i})
    xlabel('time elapsed [hh:mm:ss]','FontSize',14)
    ylabel('C_1 [-]','FontSize',14)
    set(gca, 'FontSize', 14)
    ylim([-0.02 1])
    grid on
    hold on
end
legend(legendEntries, 'Interpreter','none','FontSize',8,'Location','southeast')
title(sprintf('BT curves from CT (%s)',dataSource),'Interpreter','none')
fname = sprintf('BT_CT_%s_time',dataSource);
saveas(fig, fullfile(exportPath, fname), 'png');
saveas(fig, fullfile(exportPath, fname), 'fig');

%% BTC dimensionless time
colours = {[0.318 0.654 0.976],[0.09 0.306 0.525], [0.435 0.753 0.251],[0.059 0.361 0.102] }; %light blue, dark blue, light green, dark green

fig = figure;
legendEntries = cell(1, height(inputFileConfig));

for i = 1:height(inputFileConfig)
    filedataExp = filedataExpAll{i}; 
    vars = expCTDataAll{i}.varsAll.(dataSource);
    CfieldOutlet = 'CD1_zD1p0';

    legendEntries{i} = "CT"+filedataExp.Key;

    % plot
    plot(vars.tDtotal, vars.(CfieldOutlet),'LineWidth',2,'Color',colours{:,i})
    xlabel('t_D [-]','FontSize',14)
    ylabel('C_1 [-]','FontSize',14)
    set(gca, 'FontSize', 14)
    ylim([-0.02 1])
    xlim([0,1.2])
    grid on
    hold on
end
legend(legendEntries, 'Interpreter','none','FontSize',8,'Location','northwest')
title(sprintf('BT curves from CT (%s)',dataSource),'Interpreter','none')
fname = sprintf('BT_CT_%s_tD',dataSource);
saveas(fig, fullfile(exportPath, fname), 'png');
saveas(fig, fullfile(exportPath, fname), 'fig');

%% MFM analog BTC

colours = {[0.318 0.654 0.976],[0.09 0.306 0.525], [0.435 0.753 0.251],[0.059 0.361 0.102] }; %light blue, dark blue, light green, dark green

fig = figure;
legendEntries = cell(1, height(inputFileConfig));

for i = 1:height(inputFileConfig)
    vars_MFM_CT  = MFM_CT_DataAll{i}.BT;

    legendEntries{i} = inputFileConfig.MFM_BTC_CT_Key{i};

    % plot BT MFM CT
    plot(vars_MFM_CT.tD, vars_MFM_CT.CDi,'LineWidth',2,'Color',colours{:,i})
    xlabel('t_D [-]','FontSize',14)
    ylabel('C_1 [-]','FontSize',14)
    set(gca, 'FontSize', 14)
    ylim([-0.02 1])
    xlim([0,2])
    grid on
    hold on
end
legend(legendEntries, 'Interpreter','none','FontSize',8,'Location','northwest')
title(sprintf('BT curves from MFM analog CT-CF'),'Interpreter','none')
fname = sprintf('BT_CT_MFM_tD');
saveas(fig, fullfile(exportPath, fname), 'png');
saveas(fig, fullfile(exportPath, fname), 'fig');

%% MFM UHS BTC

colours = {[0.318 0.654 0.976],[0.09 0.306 0.525], [0.435 0.753 0.251],[0.059 0.361 0.102] }; %light blue, dark blue, light green, dark green

fig = figure;
legendEntries = cell(1, height(inputFileConfig));

for i = 1:height(inputFileConfig)
    vars_MFM_UHS  = MFM_UHS_DataAll{i}.BT;

    legendEntries{i} = inputFileConfig.MFM_BTC_UHS_Key{i};

    % plot BT MFM UHS
    plot(vars_MFM_UHS.tD, vars_MFM_UHS.CDi,'LineWidth',2,'Color',colours{:,i})
    xlabel('t_D [-]','FontSize',14)
    ylabel('C_1 [-]','FontSize',14)
    set(gca, 'FontSize', 14)
    ylim([-0.02 1])
    xlim([0,2])
    grid on
    hold on
end
legend(legendEntries, 'Interpreter','none','FontSize',8,'Location','northwest')
title(sprintf('BT curves from MFM UHS'),'Interpreter','none')
fname = sprintf('BT_UHS_MFM_tD');
saveas(fig, fullfile(exportPath, fname), 'png');
saveas(fig, fullfile(exportPath, fname), 'fig');

%% MFM analog and UHS and CT together BTC

colours = {[0.318 0.654 0.976],[0.09 0.306 0.525], [0.435 0.753 0.251],[0.059 0.361 0.102] }; %light blue, dark blue, light green, dark green

fig = figure;

for i = 1:height(inputFileConfig)
    vars_MFM_CT  = MFM_CT_DataAll{i}.BT;
    vars_MFM_UHS  = MFM_UHS_DataAll{i}.BT;

    % plot BT MFM CT and MFM UHS
    plot(vars_MFM_CT.tD, vars_MFM_CT.CDi,'--', ...
        'LineWidth',2,'Color',colours{:,i},'DisplayName',inputFileConfig.MFM_BTC_CT_Key{i})
    hold on
    plot(vars_MFM_UHS.tD, vars_MFM_UHS.CDi,':', ...
        'LineWidth',2,'Color',colours{:,i},'DisplayName',inputFileConfig.MFM_BTC_UHS_Key{i})
    xlabel('t_D [-]','FontSize',14)
    ylabel('C_1 [-]','FontSize',14)
    set(gca, 'FontSize', 14)
    ylim([-0.02 1])
    xlim([0,2])
    grid on
    
end
legend('Interpreter','none','FontSize',8,'Location','northwest')
title(sprintf('BT curves from MFM analog CT-CF'),'Interpreter','none')
fname = sprintf('BT_UHS_MFM_tD');
saveas(fig, fullfile(exportPath, fname), 'png');
saveas(fig, fullfile(exportPath, fname), 'fig');

%% width with time and theoretical

colours = {[0.318 0.654 0.976],[0.09 0.306 0.525], [0.435 0.753 0.251],[0.059 0.361 0.102]};
widthPairs = {'10_90','16_84','30_70','40_60'};

for p = 1:length(widthPairs)
    widthPair = widthPairs{p};
    measField = ['zDWidth_' widthPair];
    theorField = ['zDWidthDiff_' widthPair];

    fig = figure('Position',[100 100 1000 650]);
    for i = 1:height(inputFileConfig)
        filedataExp = filedataExpAll{i};
        vars = expCTDataAll{i}.varsAll.(dataSource);

        scatter(vars.tDtotal, vars.(measField),6, 'filled',...
            'MarkerFaceColor',colours{i}, 'DisplayName',"meas - " + filedataExp.Key)
        hold on
        plot(vars.tDtotal, vars.(theorField), '-', ...
            'LineWidth',2,'Color',colours{i}, 'DisplayName',"theor - " + filedataExp.Key)
    end
    xlabel('t_D [-]','FontSize',14)
    ylabel('dZ_D [-]','FontSize',14)
    set(gca, 'FontSize', 14)
    ylim([-0.02 1])
    xlim([0,1.2])
    grid on
    legend('Interpreter','none','FontSize',8,'Location','northeast','NumColumns',2)
    title(sprintf('width (dZ, %s) measured vs theoretical from CT (%s)', strrep(widthPair,'_','-'), dataSource),'Interpreter','none')

    fname = sprintf('width_CT_%s_%s_tD', widthPair, dataSource);
    if ~isfolder(exportPath), mkdir(exportPath); end
    saveas(fig, fullfile(exportPath, fname), 'png');
    saveas(fig, fullfile(exportPath, fname), 'fig');
end
%% Front envelope: measured (solid) and theoretical (dashed) width, centered on front position

colours = {[0.318 0.654 0.976],[0.09 0.306 0.525], [0.435 0.753 0.251],[0.059 0.361 0.102]};
darkFactor = 0.6;   % <1 = darker
coloursDark = cellfun(@(c) c*darkFactor, colours, 'UniformOutput', false);
% widthPairs = {'10_90','16_84','30_70','40_60'};
widthPairs = {'30_70','40_60'};

for p = 1:length(widthPairs)
    widthPair = widthPairs{p};
    measField = ['zDWidth_' widthPair];
    theorField = ['zDWidthDiff_' widthPair];

    for i = 1:height(inputFileConfig)
        fig = figure('Position',[100 100 1000 650]); hold on
        filedataExp = filedataExpAll{i};
        vars = expCTDataAll{i}.varsAll.(dataSource);

        tD = vars.tDtotal;
        centerMeas = vars.zDFront50;
        halfMeas = vars.(measField) / 2;
        centerTheor = vars.zDFront_theory;
        halfTheor = vars.(theorField) / 2;

        % measured segments (solid), only where width exists
        for k = 1:height(vars)
            if isnan(centerMeas(k)) || isnan(halfMeas(k)), continue; end
            plot([tD(k) tD(k)], [centerMeas(k)-halfMeas(k), centerMeas(k)+halfMeas(k)], ...
                '-', 'Color',[colours{i} 0.8], 'LineWidth',1.5, 'HandleVisibility','off')
        end
        validMeas = ~isnan(centerMeas) & ~isnan(halfMeas);
        scatter(tD(validMeas), centerMeas(validMeas), 20, coloursDark{i}, 'filled', ...
            'DisplayName',"meas - " + filedataExp.Key)

        % theoretical segments, only where width exists
        for k = 1:height(vars)
            if isnan(centerTheor(k)) || isnan(halfTheor(k)), continue; end
            plot([tD(k) tD(k)], [centerTheor(k)-halfTheor(k), centerTheor(k)+halfTheor(k)], ...
                '-', 'Color',[colours{i} 0.8], 'LineWidth',1.2, 'HandleVisibility','off')
        end
        validTheor = ~isnan(centerTheor) & ~isnan(halfTheor);
        scatter(tD(validTheor), centerTheor(validTheor), 30, coloursDark{i}, 'x', 'LineWidth',1.5, ...
            'DisplayName',"theor - " + filedataExp.Key)

        xlabel('t_D [-]','FontSize',14)
        ylabel('z_D [-]','FontSize',14)
        set(gca, 'FontSize', 14)
        ylim([-0.02 1.02])
        xlim([0,1.2])
        grid on
        legend('Interpreter','none','FontSize',8,'Location','southwest','NumColumns',2)
        title(sprintf('Front envelope (%s) - %s: measured vs theoretical, centered on front position (%s)', ...
            strrep(widthPair,'_','-'), filedataExp.Key, dataSource),'Interpreter','none')

        fname = sprintf('frontEnvelope_CT_%s_%s_%s_tD', filedataExp.Key, widthPair, dataSource);
        saveas(fig, fullfile(exportPath, fname), 'png');
        saveas(fig, fullfile(exportPath, fname), 'fig');
    end
end
%% Front tilt and shape diagnostics vs tD

colours = {[0.318 0.654 0.976],[0.09 0.306 0.525], [0.435 0.753 0.251],[0.059 0.361 0.102]};

fig = figure('Position',[100 100 650 1200]);

subplot(2,1,1); hold on
for i = 1:nExp
    filedataExp = filedataExpAll{i};
    vars = expCTDataAll{i}.varsAll.(dataSource);
    plot(vars.tDtotal, vars.frontTiltSlope, 'o-', 'LineWidth',1.5, 'Color',colours{i}, ...
        'DisplayName', char(filedataExp.Key))
end
xlabel('t_D [-]','FontSize',12)
ylabel('front tilt slope [z_D/x_D]','FontSize',12)
title('Front tilt vs t_D','FontSize',12)
grid on
legend('Interpreter','none','FontSize',8,'Location','northeast')

subplot(2,1,2); hold on
for i = 1:nExp
    filedataExp = filedataExpAll{i};
    vars = expCTDataAll{i}.varsAll.(dataSource);
    plot(vars.tDtotal, vars.frontArcLengthRatio, 's-', 'LineWidth',1.5, 'Color',colours{i}, ...
        'DisplayName', char(filedataExp.Key))
end
yline(1, ':k', 'LineWidth',1, 'DisplayName','perfectly flat')
xlabel('t_D [-]','FontSize',12)
ylabel('arc length ratio [-]','FontSize',12)
title('Front non-planarity (shape-agnostic) vs t_D','FontSize',12)
grid on
legend('Interpreter','none','FontSize',8,'Location','northeast')

sgtitle(sprintf('Front planarity diagnostics (%s)', dataSource),'Interpreter','none')
fname = sprintf('frontTiltShape_%s_tD', dataSource);
saveas(fig, fullfile(exportPath, fname), 'png');
saveas(fig, fullfile(exportPath, fname), 'fig');

%% KL_CT vs tD, across all experiments — now populated at every scan

colours = {[0.318 0.654 0.976],[0.09 0.306 0.525], [0.435 0.753 0.251],[0.059 0.361 0.102]};

fig = figure('Position',[100 100 1000 650]); hold on
for i = 1:nExp
    filedataExp = filedataExpAll{i};
    vars = expCTDataAll{i}.varsAll.(dataSource);

    valid = ~isnan(vars.KL_CT);
    plot(vars.tDtotal(valid), vars.KL_CT(valid), 'o-', 'LineWidth',1.5, ...
        'Color',colours{i}, 'MarkerSize',4, 'DisplayName', char(filedataExp.Key))
end
xlabel('t_D [-]','FontSize',14)
ylabel('K_L from \sigma [cm^2/min]','FontSize',14)
set(gca,'FontSize',14)
grid on
legend('Interpreter','none','FontSize',9,'Location','best')
title(sprintf('K_L from front moments vs t_D (%s)', dataSource),'Interpreter','tex')

fname = sprintf('KL_front_%s_tD', dataSource);
saveas(fig, fullfile(exportPath, fname), 'png');
saveas(fig, fullfile(exportPath, fname), 'fig');

%% BTC width at outlet (zD=1.0): time-domain width, one row per experiment

colours = {[0.318 0.654 0.976],[0.09 0.306 0.525], [0.435 0.753 0.251],[0.059 0.361 0.102]};
darkFactor = 0.6;
coloursDark = cellfun(@(c) c*darkFactor, colours, 'UniformOutput', false);

fig = figure('Position',[100 100 1000 650]); hold on

yLabels = cell(height(inputFileConfig),1);

for i = 1:height(inputFileConfig)
    filedataExp = filedataExpAll{i};
    metrics = expCTDataAll{i}.resultsAll.(dataSource).BTCMetrics;

    tD16 = metrics.tD16;
    tD50 = metrics.tD50;
    tD84 = metrics.tD84;

    yPos = i;   % row position = experiment index

    plot([tD16 tD84], [yPos yPos], '-', 'Color',[colours{i} 0.8], 'LineWidth',3, 'HandleVisibility','off')
    scatter(tD50, yPos, 40, coloursDark{i}, 'filled', 'DisplayName', char(filedataExp.Key))

    yLabels{i} = char(filedataExp.Key);
end

xlabel('t_D [-]','FontSize',14)
ylabel('Experiment','FontSize',14)
set(gca, 'FontSize', 14)
yticks(1:height(inputFileConfig))
yticklabels(yLabels)
set(gca, 'TickLabelInterpreter', 'none')
ylim([0.5, height(inputFileConfig)+0.5])
xlim([0,1.5])
grid on
title(sprintf('Outlet BTC width (16-84%%), centered on tD=0.5 (%s)', dataSource),'Interpreter','none')

fname = sprintf('BTCwidth_outlet_%s_tD', dataSource);
saveas(fig, fullfile(exportPath, fname), 'png');
saveas(fig, fullfile(exportPath, fname), 'fig');

%% add plot KL/D0 vs Pe v*L/KL for all : MFM UHS, MFM analog, BTC CT, profile average CT
