%% CT Concentration Analysis and Transport Metrics Extraction
%
% This script extracts quantitative transport information from processed
% concentration images generated from CT experiments.
%
% Concentration images previously stored in HDF5 format are analyzed to
% compute spatial concentration profiles, breakthrough curves, mixing-zone
% characteristics, and concentration-front velocities.
%
% The resulting variables are consolidated into a structured MATLAB object
% and saved for downstream visualization and comparative analysis.
%
% Workflow
% --------
% 1. Import experiment metadata and configuration.
% 2. Load scanner metadata (.pca, .pcj, .pcp).
% 3. Read concentration images from HDF5 storage.
% 4. Compute concentration statistics for each image:
%       - Axial concentration profile
%       - Vertical concentration profile
%       - Concentration histogram
%       - Injected pore volumes
%       - Dimensionless time
% 5. Determine concentration-front locations:
%       - C = 0.1 front
%       - C = 0.9 front
%       - Front width
% 6. Construct breakthrough curves.
% 7. Estimate front propagation velocity.
% 8. Generate contour-based front maps.
% 9. Compute apparent velocity fields from contour displacement.
% 10. Save all processed variables into a MATLAB structure.
%
% Inputs
% ------
% inputCTExpConfig.xlsx
%     Repository configuration file.
%
% Processed HDF5 files
%     Generated by the image processing workflow and containing:
%
%         /exp/run_xx/conc
%
%     where each dataset is a stack of concentration images.
%
% Scanner Metadata
% ----------------
% .pca
%     Scanner and reconstruction parameters.
%
% .pcp
%     Acquisition timestamps and scan information.
%
% .pcj
%     Reconstruction metadata.
%
% Outputs
% -------
% One MAT file per experiment:
%
%     <ExperimentKey>.mat
%
% containing:
%
%     CFparams
%     BTlinesBefore
%     BTcore
%     concVarsAll
%     refInit
%     refFinal
%     exp
%
% Key Quantities Calculated
% -------------------------
%
% C1Profile
%     Cross-sectionally averaged concentration as a function of core
%     length:
%
%         C1(z)
%
% C1Axial
%     Laterally averaged concentration as a function of horizontal
%     position:
%
%         C1(x)
%
% BTcore
%     Breakthrough curve based on outlet concentration.
%
% BTlinesBefore
%     Breakthrough curve based on inlet concentration.
%
% zFront10
%     Mean position of the C = 0.1 concentration contour.
%
% zFront90
%     Mean position of the C = 0.9 concentration contour.
%
% zWidth
%     Mixing-zone width:
%
%         zWidth = zFront10 - zFront90
%
% tDcorr
%     Corrected dimensionless time based on measured front velocity.
%
% Velocity Field Analysis
% -----------------------
%
% Concentration contours from:
%
%     C = 0.1, 0.2, ..., 0.9
%
% are tracked between consecutive images.
%
% Displacements are converted into:
%
%     Vz_field   Vertical front velocity [cm/s]
%     Vx_field   Lateral front velocity [cm/s]
%
% providing a simple estimate of concentration-front motion throughout
% the experiment.
%
% Dependencies
% ------------
%
%     import_inputCTExp
%     importPCA
%     importPCP
%     importPCJ
%
% MATLAB Functions
% ----------------
%
%     h5read
%     h5info
%     histcounts
%     gradient
%
% Notes
% -----
%
% Front positions are estimated using concentration bands:
%
%     0.05 ≤ C ≤ 0.15   -> C = 0.1 front
%     0.85 ≤ C ≤ 0.95   -> C = 0.9 front
%
% Concentration contour maps are generated using concentration intervals:
%
%     C = 0.1 : 0.1 : 0.9
%
% These contour maps are used solely for front tracking and velocity-field
% estimation.

%% IMPORT input

addpath('functions/');

% Introduce name of input and desired output folder name

inputFileConfigName = 'inputCTExpConfig.xlsx';
inputFileConfig = readtable(inputFileConfigName);

filenameExp = inputFileConfig.inputFileName{:};

pathImportAll = inputFileConfig.importPath{:}; % Path for OUTPUT
pathExportAll = inputFileConfig.exportPath{:}; % Path for OUTPUT
mkdir(pathExportAll); % Create directory for output

%% Extract data from images

filedataExp = import_inputCTExp(filenameExp); % import input to a local variable

% Capture init ref data folder
refInitFolderContent = dir(filedataExp.path+filedataExp.CT_data_ref_init); % Xe
refInitFolderContent = refInitFolderContent([refInitFolderContent.isdir] & ~startsWith({refInitFolderContent.name},'.'));
refInitFolderName = refInitFolderContent.name;

% Capture final ref data folder
refFinalFolderContent = dir(filedataExp.path+filedataExp.CT_data_ref_final); % He
refFinalFolderContent = refFinalFolderContent([refFinalFolderContent.isdir] & ~startsWith({refFinalFolderContent.name},'.'));
refFinalFolderName = refFinalFolderContent.name;

% Capture exp data folder
expFolderContent = dir(filedataExp.path+filedataExp.CT_data_exp); % exp
expFolderContent = expFolderContent([expFolderContent.isdir] & ~startsWith({expFolderContent.name},'.'));
expFolderName = {expFolderContent.name}';
expFolderPath = {expFolderContent.folder};

% BT extract
BTlinesBefore = table(); 
BTcore = table();
expCTData = struct();

for i = 1:length(filedataExp.Key)

    % Image
    HDF5filename = fullfile(pathExportAll, filedataExp.Key(i) + ".h5");

    % CF params
    expCTData.(filedataExp.Key(i)).CFparams = filedataExp(i,:);

    % CT init ref
    refInitFolderPathCT = fullfile(refInitFolderContent.folder, refInitFolderName);
        % pca
        refInitpcaFiles = dir(fullfile(refInitFolderPathCT, '*.pca'));
        expCTData.(filedataExp.Key(i)).refInit.pca = importPCA(refInitpcaFiles);
        % pcj 
        refInitpcjFiles = dir(fullfile(refInitFolderPathCT, '*.pcj'));
        expCTData.(filedataExp.Key(i)).refInit.pcj = importPCJ(refInitpcjFiles);
        % pcp
        refInitpcpFiles = dir(fullfile(refInitFolderPathCT, '*.pcp'));
        expCTData.(filedataExp.Key(i)).refInit.pcp = importPCP(refInitpcpFiles);
        % CTimages folder 
        
    nn_refInit = height(expCTData.(filedataExp.Key(i)).refInit.pcp);

    % CT final ref
    refFinalFolderPathCT = fullfile(refFinalFolderContent.folder, refFinalFolderName);
        % pca
        refFinalpcaFiles = dir(fullfile(refFinalFolderPathCT, '*.pca'));
        expCTData.(filedataExp.Key(i)).refFinal.pca = importPCA(refFinalpcaFiles);
        % pcj 
        refFinalpcjFiles = dir(fullfile(refFinalFolderPathCT, '*.pcj'));
        expCTData.(filedataExp.Key(i)).refFinal.pcj = importPCJ(refFinalpcjFiles);
        % pcp
        refFinalpcpFiles = dir(fullfile(refFinalFolderPathCT, '*.pcp'));
        expCTData.(filedataExp.Key(i)).refFinal.pcp = importPCP(refFinalpcpFiles);

    % BT concvarsAll
    concVarsAll = table();

    for j = 1:length(expFolderName)
        expFolderPathCT = fullfile(expFolderPath{j}, expFolderName{j});
        run_name = "run_" + sprintf('%02d', j);
            % pca
            exppcaFiles = dir(fullfile(expFolderPathCT, '*.pca'));
            expCTData.(filedataExp.Key(i)).exp.(run_name).pca = importPCA(exppcaFiles);
            % pcj 
            exppcjFiles = dir(fullfile(expFolderPathCT, '*.pcj'));
            expCTData.(filedataExp.Key(i)).exp.(run_name).pcj = importPCJ(exppcjFiles);
            % pcp
            exppcpFiles = dir(fullfile(expFolderPathCT, '*.pcp'));
            expCTData.(filedataExp.Key(i)).exp.(run_name).pcp = importPCP(exppcpFiles);

        nn_exp = height(expCTData.(filedataExp.Key(i)).exp.(run_name).pcp); % per run

        HDF5dataPath = ['/exp/' char(run_name) '/conc'];  % structured path
        info = h5info(HDF5filename, HDF5dataPath);
        dims = info.Dataspace.Size;
        nx = dims(1);
        ny = dims(2);
        nz = dims(3);

        for k = 1:nn_exp
            concImage = h5read(HDF5filename, HDF5dataPath, [1 1 k], [nx ny 1]);

            % Concentration profiles and histograms of normalized images
            imgNr = expCTData.(filedataExp.Key(i)).exp.(run_name).pcp.ImgNr(k);
            rotPos = expCTData.(filedataExp.Key(i)).exp.(run_name).pcp.RotPos(k);
            timeStamp = expCTData.(filedataExp.Key(i)).exp.(run_name).pcp.Time(k);
            timeStart = filedataExp.st(i);
            timeElapsed = timeStamp - timeStart;
            secondsElapsed = seconds(timeElapsed);
            volInjected = secondsElapsed*filedataExp.Q(i)/60;
            tDtotal = volInjected/filedataExp.Vtotal(i);
            % ct prop
            resXmm = expCTData.(filedataExp.Key(i)).exp.(run_name).pca.Geometry.VoxelSizeX; % mm
            resYmm = expCTData.(filedataExp.Key(i)).exp.(run_name).pca.Geometry.VoxelSizeY; % mm
            % histogram 
            numBins = 100;
            [counts, edges] = histcounts(concImage, numBins);
            % y vars
            concVert = mean(concImage');
            pixelVert = 1:1:length(concVert);
            zVertcm = pixelVert*resYmm/10; %cm
            % x vars
            concHorz = mean(concImage);
            pixelHorz = 1:1:length(concHorz);
            xHorzcm = pixelHorz*resXmm/10; %cm
            % store in struct
            expCTData.(filedataExp.Key(i)).exp.(run_name).concVars(k).imgNr = imgNr;
            expCTData.(filedataExp.Key(i)).exp.(run_name).concVars(k).rotPos = rotPos;
            expCTData.(filedataExp.Key(i)).exp.(run_name).concVars(k).timeStamp = timeStamp;
            expCTData.(filedataExp.Key(i)).exp.(run_name).concVars(k).timeElapsed = timeElapsed;     
            expCTData.(filedataExp.Key(i)).exp.(run_name).concVars(k).secondsElapsed = secondsElapsed; 
            expCTData.(filedataExp.Key(i)).exp.(run_name).concVars(k).volInjected = volInjected;
            expCTData.(filedataExp.Key(i)).exp.(run_name).concVars(k).tDtotal = tDtotal;
            expCTData.(filedataExp.Key(i)).exp.(run_name).concVars(k).histImage = [counts', edges(1:end-1)',edges(2:end)']; % hist
            expCTData.(filedataExp.Key(i)).exp.(run_name).concVars(k).C1Profile = [zVertcm',concVert']; % y vars
            expCTData.(filedataExp.Key(i)).exp.(run_name).concVars(k).C1Axial = [xHorzcm',concHorz']; % x vars
            % front velocity
            % C = 0.1
            idx = (concImage>=0.05 & concImage <= 0.15);
            [rows, ~] = find(idx);   % rows = Z positions (pixel indices)
            if ~isempty(rows)
                zFront_10 = mean(rows) * resYmm / 10;
            else
                zFront_10 = NaN;
            end
                        % C = 0.1
            idx = (concImage>=0.85 & concImage <= 0.95);
            [rows, ~] = find(idx);   % rows = Z positions (pixel indices)
            if ~isempty(rows)
                zFront_90 = mean(rows) * resYmm / 10;
            else
                zFront_90 = NaN;
            end
            zWidth = zFront_10 - zFront_90;

            expCTData.(filedataExp.Key(i)).exp.(run_name).concVars(k).zFront10 = zFront_10; % Z C = 0.1 front
            expCTData.(filedataExp.Key(i)).exp.(run_name).concVars(k).zFront90 = zFront_90; % Z C = 0.9 front
            expCTData.(filedataExp.Key(i)).exp.(run_name).concVars(k).zWidth = zWidth; % Z width front from 0.9 to 0.1

            % 2D velocity field from iso-concentration contours
            concLevels = 0.1:0.1:0.9;   % contour levels to track
            nLevels    = length(concLevels);
            [nRows, nCols] = size(concImage);        
            zFrontMap = NaN(nLevels, nCols);   % z position (cm) per level per column
            xFrontMap = NaN(nLevels, nCols);   % x position (cm) — column coordinate  
            halfBand = 0.05;   % half-width of concentration band around each level
            for lv = 1:nLevels
                cLow  = concLevels(lv) - halfBand;
                cHigh = concLevels(lv) + halfBand;
                for col = 1:nCols
                    colData = concImage(:, col);   % concentration vs z for this column
                    idx = find(colData >= cLow & colData <= cHigh);
                    if ~isempty(idx)
                        zFrontMap(lv, col) = mean(idx) * resYmm / 10;   % cm
                    end
                    xFrontMap(lv, col) = col * resXmm / 10;             % cm
                end
            end
            expCTData.(filedataExp.Key(i)).exp.(run_name).concVars(k).zFrontMap = zFrontMap;
            expCTData.(filedataExp.Key(i)).exp.(run_name).concVars(k).xFrontMap = xFrontMap;
            expCTData.(filedataExp.Key(i)).exp.(run_name).concVars(k).concLevels = concLevels;

            % BT
            BTlinesBefore_temp = table( timeStamp, timeElapsed, secondsElapsed, volInjected, tDtotal, concVert(1),...
                'VariableNames',{'timeStamp','timeElapsed','secondsElapsed','volInjected','tDtotal','C1'});
            BTcore_temp = table( timeStamp, timeElapsed, secondsElapsed, volInjected, tDtotal, concVert(end),zFront_10,zFront_90,zWidth,...
                'VariableNames',{'timeStamp','timeElapsed','secondsElapsed','volInjected','tDtotal','C1','zFront10','zFront90','zWidth'});
            BTlinesBefore = [BTlinesBefore;BTlinesBefore_temp];
            BTcore = [BTcore;BTcore_temp];
        
        end

        % Velocity field from contour displacement between frames
        nFrames = nn_exp;
        concVarsRun = expCTData.(filedataExp.Key(i)).exp.(run_name).concVars;
        % Preallocate velocity arrays: [nLevels x nCols x nFrames]
        Vz_field = NaN(nLevels, nCols, nFrames);
        Vx_field = NaN(nLevels, nCols, nFrames);

        for k = 2:nFrames
            dt = concVarsRun(k).secondsElapsed - concVarsRun(k-1).secondsElapsed;
            if dt == 0, continue; end
        
            zCurr = concVarsRun(k).zFrontMap;    % [nLevels x nCols]
            zPrev = concVarsRun(k-1).zFrontMap;
            xCurr = concVarsRun(k).xFrontMap;
            xPrev = concVarsRun(k-1).xFrontMap;
        
            Vz_field(:,:,k) = (zCurr - zPrev) / dt;   % cm/s  — vertical (downward = positive)
            Vx_field(:,:,k) = (xCurr - xPrev) / dt;   % cm/s  — lateral drift
        end

        expCTData.(filedataExp.Key(i)).exp.(run_name).Vz_field = Vz_field;
        expCTData.(filedataExp.Key(i)).exp.(run_name).Vx_field = Vx_field;
        expCTData.(filedataExp.Key(i)).exp.(run_name).xFrontMap_ref = concVarsRun(end).xFrontMap;
        expCTData.(filedataExp.Key(i)).exp.(run_name).zFrontMap_ref = concVarsRun(end).zFrontMap;

        concVars_temp =  expCTData.(filedataExp.Key(i)).exp.(run_name).concVars;
        concVars_tempTable = struct2table(concVars_temp,'AsArray',true);
        concVarsAll = [concVarsAll;concVars_tempTable];


    end
    expCTData.(filedataExp.Key(i)).BTlinesBefore = BTlinesBefore;
    expCTData.(filedataExp.Key(i)).BTcore = BTcore;
    expCTData.(filedataExp.Key(i)).concVarsAll = concVarsAll;

    velFront_cms = mean(gradient(expCTData.(filedataExp.Key(i)).concVarsAll.zFront10, ...
        expCTData.(filedataExp.Key(i)).concVarsAll.secondsElapsed),'omitnan');
    velFront_cmmin = velFront_cms*60;
    expCTData.(filedataExp.Key(i)).CFparams.velFront_cmmin = velFront_cmmin;
    expCTData.(filedataExp.Key(i)).concVarsAll.tDcorr = ...
        velFront_cms*expCTData.(filedataExp.Key(i)).concVarsAll.secondsElapsed/zVertcm(end);
    for j = 1:length(expFolderName)
        run_name = "run_" + sprintf('%02d', j);
        for k = 1:nn_exp
            expCTData.(filedataExp.Key(i)).exp.(run_name).concVars(k).tDcorr = ...
                velFront_cms*expCTData.(filedataExp.Key(i)).exp.(run_name).concVars(k).secondsElapsed/zVertcm(end);
        end
    end

    % save expCTData
    expCT_name = pathExportAll + filedataExp.Key(i);
    expCTDataSave = expCTData.(filedataExp.Key(i));
    save(expCT_name + '.mat','expCTDataSave')
end
