
%% Comparative Analysis of CT-Derived Concentration Profiles
%
% This script compares concentration distributions and breakthrough curves
% from multiple CT experiments. Experimental results are loaded from
% previously processed MATLAB datasets and plotted together to facilitate
% comparison between experimental conditions.
%
% Workflow
% --------
% 1. Load experiment configurations from a master spreadsheet.
% 2. Import processed concentration data for each experiment.
% 3. Search for the concentration profile closest to a user-defined
%    concentration-location target.
% 4. Extract the selected concentration profile.
% 5. Plot concentration profiles from all experiments.
% 6. Plot corresponding breakthrough curves for comparison.
%
% Analysis Performed
% ------------------
%
% Profile Selection:
%   For each experiment, the script searches all available concentration
%   profiles and identifies the profile whose concentration distribution
%   passes closest to a specified target coordinate:
%
%       (Z_target, C_target)
%
%   This allows profiles from different experiments to be compared at
%   approximately equivalent displacement states.
%
% Concentration Profile Comparison:
%   Displays averaged concentration profiles along the core length:
%
%       C1(Z)
%
%   for the selected experimental state.
%
% Breakthrough Curve Comparison:
%   Displays outlet concentration as a function of time:
%
%       C1(t)
%
%   allowing comparison of displacement dynamics between experiments.
%
% Inputs
% ------
% inputCTExpConfig.xlsx
%     Configuration file containing paths to processed experimental data.
%
% Experiment MAT Files
%     Generated by the CT processing workflow and containing:
%
%         concVarsAll
%         BTcore
%         CFparams
%
% User Parameters
% ---------------
% Z_target
%     Target axial position [cm].
%
% C_target
%     Target concentration [-].
%
% Outputs
% -------
% Figure 1:
%     Comparison of selected axial concentration profiles.
%
% Figure 2:
%     Comparison of breakthrough curves.
%
% Dependencies
% ------------
%     import_inputCTExp
%
% Notes
% -----
% The profile selected for each experiment corresponds to the minimum
% Euclidean distance:
%
%     d² = (Z - Z_target)² + (C - C_target)²
%
% between the profile and the target reference point.


%% IMPORT input

CT_setupPaths;

% Introduce name of input and desired output folder name

inputFileConfigName = 'inputCTExpConfig.xlsx';
inputFileConfig = readtable(inputFileConfigName);
exportPath = 'results/';

%% Find where to plot profile
% Plot Z Profile at fixed zD

colours = {[0.318 0.654 0.976],[0.09 0.306 0.525], [0.435 0.753 0.251],[0.059 0.361 0.102] }; %light blue, dark blue, light green, dark green

ZD_target = 0.5;
CD_target = 0.5;

ZD_found = [];
CD_found = [];
idx_found = [];
l_found = [];

figure
legendEntries = cell(1, height(inputFileConfig));

for i = 1:height(inputFileConfig)
    filenameExp = inputFileConfig.inputFileName{i};
    pathExportAll = inputFileConfig.exportPath{i}; % Path for OUTPUT
    filedataExp = import_inputCTExp(filenameExp); % import input to a local variable

    expCTDataname = fullfile(pathExportAll, filedataExp.Key + ".mat");
    expCTDataTemp = load(expCTDataname);
    expCTData.(filedataExp.Key) = expCTDataTemp.expCTDataSave;

    vars = expCTData.(filedataExp.Key).concVarsAll;

    best_dist = inf;
    best_ZD = NaN;
    best_CD = NaN;
    best_idx = NaN;
    best_l = NaN;

    for l = 1:height(vars)

        C1Profile = vars.C1Profile{l};

        ZD = C1Profile.zDimLess;
        CD = C1Profile.rhoNormVert;

        dist = (ZD - ZD_target).^2 + (CD - CD_target).^2;

        [min_dist, idx] = min(dist);

        if min_dist < best_dist
            best_dist = min_dist;
            best_ZD = ZD(idx);
            best_CD = CD(idx);
            best_idx = idx;
            best_l = l;
        end
    end

    ZD_found(i) = best_ZD;
    CD_found(i) = best_CD;
    idx_found(i) = best_idx;
    l_found(i) = best_l;

    % what profile to plot
    C1Profile_plot = vars.C1Profile{l_found(i)};
    tD = vars.tDtotal(l_found(i));
    legendEntries{i} = filedataExp.Key;

    % plot
    plot(C1Profile_plot.zDimLess, C1Profile_plot.rhoNormVert,'LineWidth',3,'Color',colours{:,i})
    xlabel('Z_D [-]','FontSize',14)
    ylabel('C_1 [-]','FontSize',14)
    set(gca, 'FontSize', 14)
    grid on
    hold on

end
legend(legendEntries, 'Interpreter','none','FontSize',9.8)

%% Find where to plot profile
% Plot Z Profile at fixed tD

colours = {[0.318 0.654 0.976],[0.09 0.306 0.525], [0.435 0.753 0.251],[0.059 0.361 0.102] }; %light blue, dark blue, light green, dark green
% tD_target = 0.5;
tD_target = 0.5:0.1:1;

for m=1:length(tD_target)
    tD_found = nan(height(inputFileConfig),1);
    l_found  = nan(height(inputFileConfig),1);
    
    fig = figure;
    legendEntries = cell(1, height(inputFileConfig));
    
    for i = 1:height(inputFileConfig)
        filenameExp = inputFileConfig.inputFileName{i};
        pathExportAll = inputFileConfig.exportPath{i}; % Path for OUTPUT
        filedataExp = import_inputCTExp(filenameExp); % import input to a local variable
    
        expCTDataname = fullfile(pathExportAll, filedataExp.Key + ".mat");
        expCTDataTemp = load(expCTDataname);
        expCTData.(filedataExp.Key) = expCTDataTemp.expCTDataSave;
    
        vars = expCTData.(filedataExp.Key).concVarsAll;
    
        % find the scan (row) whose tDtotal is closest to target
        [minDist, l] = min(abs(vars.tDtotal - tD_target(m)));
        if minDist > 0.05   % flag if the nearest available scan is far from target
            warning('%s: nearest scan is tD=%.3f (target %.3f, off by %.3f)', ...
                filedataExp.Key, vars.tDtotal(l), tD_target(m), minDist);
        end
    
        tD_found(i) = vars.tDtotal(l);
        l_found(i)  = l;
    
        % plot that scan's spatial profile
        C1Profile_plot = vars.C1Profile{l};
        legendEntries{i} = char(filedataExp.Key) + sprintf(" (t_D=%.2f)", tD_found(i));
    
        % plot
        plot(C1Profile_plot.zDimLess, C1Profile_plot.rhoNormVert,'LineWidth',3,'Color',colours{:,i})
        xlabel('Z_D [-]','FontSize',14)
        ylabel('C_1 [-]','FontSize',14)
        xlim([0,1])
        ylim([0,1])
        set(gca, 'FontSize', 14)
        grid on
        hold on
    
    end
    legend(legendEntries, 'Interpreter','none','FontSize',9.8)
    title(sprintf('Z profiles @ t_D = %.1f', tD_target(m)),'Interpreter','none')
    % save the completed figure for this selection
    tDStr = strrep(sprintf('%.1f', tD_target(m)), '.', 'p');  % e.g. 0.50 -> 0p50
    fname = sprintf('Zprofiles_tD%s', tDStr);
    saveas(fig, fullfile(exportPath, fname), 'png');
    saveas(fig, fullfile(exportPath, fname), 'fig');
end


%% to do plot BT dimension time
colours = {[0.318 0.654 0.976],[0.09 0.306 0.525], [0.435 0.753 0.251],[0.059 0.361 0.102] }; %light blue, dark blue, light green, dark green

figure
legendEntries = cell(1, height(inputFileConfig));

for i = 1:height(inputFileConfig)
    filenameExp = inputFileConfig.inputFileName{i};
    pathExportAll = inputFileConfig.exportPath{i}; % Path for OUTPUT
    filedataExp = import_inputCTExp(filenameExp); % import input to a local variable

    expCTDataname = fullfile(pathExportAll, filedataExp.Key + ".mat");
    expCTDataTemp = load(expCTDataname);
    expCTData.(filedataExp.Key) = expCTDataTemp.expCTDataSave;

    vars = expCTData.(filedataExp.Key).BTcore;

    legendEntries{i} = filedataExp.Key;

    % plot
    plot(vars.timeElapsed, vars.C1,'LineWidth',3,'Color',colours{:,i})
    xlabel('time elapsed [hh:mm:ss]','FontSize',14)
    ylabel('C_1 average [-]','FontSize',14)
    set(gca, 'FontSize', 14)
    ylim([-0.02 1])
    grid on
    hold on

end
legend(legendEntries, 'Interpreter','none','FontSize',9.8,'Location','southeast')

%% MFM analog and UHS and CT together BTC

%% width with time and theoretical ---
% add theoretical to main_CTpreproc
% add rhonorm and Cnorm (both) to be able to compare when Z is not
% corrected
% add uncertainty He/Xe mixture to estimation